### ISSUE TITLE
Request to Google Translate basic always uses Japanese as source language Irrespective of User Settings

### ISSUE THREAD

**Issue by creature93x** [killkimno/MORT#16]

**Comment by killkimno** [comment]
1. Please check the OCR language - if it is in Japanese, Japanese will be used as the source by default.
2. Look at your translation settings - check your source language
3. Did you click apply? Changed settings will not be applied until you press Apply.
4. I need more detailed explanation to solve this problem

**Comment by creature93x** [comment]
"Yes, I have did all the mentioned above. Please attempt to log the value of 'translate.googleapis.com/translate_a/single?client={clientType}&sl={transCode}&tl={resultCode}&dt=t&q={RestSharp.Extensions.StringExtensions.UrlEncode(original)}' used within the 'MORT\TransAPI\GoogleBasicTranslateAPI.cs' file. It's worth noting that the 'sl={transCode}' portion of the URL in the sent parameter consistently remains as 'sl=ja'" regardless of user settings.

###########

my configuration: 
#SKIN = @layer
#TESS_DATA = @eng
#USE_FAST_TESS = @False
#SHOW_OCR_RESULT = @False
#SAVE_OCR_RESULT = @True
#STRING_TOUPPER = @False
#USE_ENG = @False
#USE_JPN = @False
#USE_OTHER_LANG = @True
#NAVER_TRANS_CODE = @en
#NAVER_RESULT_CODE = @en
#NAVER_API_TYPE = @NMT
#GOOGLE_TRANS_CODE = @en
#GOOGLE_RESULT_CODE = @ar
#DEEPL_TRANS_CODE = @en
#DEEPL_RESULT_CODE = @tr
#WINDOW_OCR_LANGUAGE = @fr-FR
#USE_PARTIAL_DB = @False
#SAVE_IN_CLIPBOARD = @False
#OCR_SPEED = @2
#OCR_TPYE = @Window
#TRANS_TPYE = @google_url
#DB_FILE = @empty.txt
#DIC_FILE =@myDic.txt
#USE_DIC = @True
#MATCHING_WORD_DIC = @True
#USE_ERODE = @False
#COLOR_GROUP = @1
#RGB = @False
0
0
0
#HSV = @False
0
0
0
0
#THRESHOLD = @False
#THRESHOLD_VALUE = @127
#OCR_GROUP = @0
#OCR_EXCEPTION_GROUP = @0
#USE_OCR_COLOR_GROUP = @0
#TEXT_SORT = @Normal
#USE_REMOVE_SPACE = @False
#SHOW_OCR_INDEX = @False
#FONT_NAME = @Malgun Gothic
#FONT_SIZE = @22
#TEXT_COLOR = @
255
0
0
0
#OUTLINE1_COLOR = @
255
0
0
0
#OUTLINE2_COLOR = @
255
255
255
255
#BACK_COLOR = @True
145
255
255
255
#USE_ACTIVE_WINDOW = @False
#IMG_ZOOM_SIZE = @2,0
#USE_TTS = @False
#WAIT_TTS_END = @False
#TRANS_LOCATION_X = @1375
#TRANS_LOCATION_Y = @910
#TRANS_SIZE_X = @973
#TRANS_SIZE_Y = @240

**Comment by killkimno** [comment]
first
Because of the translation memory feature, previously translated results may continue to appear.
close mort
delete UserData/transResult_google_url.txt
and re open mort

second
#WINDOW_OCR_LANGUAGE = @FR-fr
#GOOGLE_TRANS_CODE = @en
#GOOGLE_RESULT_CODE = @ar

do you want to French to Turkish?
or english to Turkish

if you wnat to english to Turkish you should download english language pack, and setting
https://blog.naver.com/killkimno/220865537274


last

disable this function (Additional -> Advenced Setting -> Translation)

![image](https://github.com/killkimno/MORT/assets/7446259/79a94251-35c7-495b-8c96-c3f0aee49ae7)

**Comment by creature93x** [comment]
ahh i have that was the issue thank you for the solution!
